# pycodestyle (`E`, `W`), Pyflakes (`F`), Isort (`I`), Bandit (`S`),
# Pandas (`PD`), Print (`T20`).
lint.select = ["E", "W", "F", "I", "S", "PD", "T20"]
# PD901: dataframe variable name
# PD011: use to_numpy() instead of .values
lint.ignore = ["PD901", "PD011"]

# Exclude a variety of commonly ignored directories.
exclude = [".venv"]

# Same as Black.
line-length = 91

# Assume Python 3.8
target-version = "py38"
